In [149]:
import os
from chemicals.chemical import Chemical
from database.database import Database, LiquidMasterDataSet
from pprint import pprint, PrettyPrinter
import numpy as np
import pandas as pd

pp = PrettyPrinter(width=80, compact=True)
%reload_ext autoreload
%autoreload 1
%aimport utils.chemicals
%aimport database.database

Inorganic content refers to all elements except carbon and hydrogen and lithium. Organic content refers to only carbon. InOr is a ratio between inorganic content and organic content. Hydrogen and lithium were excluded from the two categories, because they are well known to be present in both organic and inorganic materials.

In [40]:
db = Database(db="FMT")
df = db.pull(table="Liquid Master Table")

In [63]:
ds_lm = LiquidMasterDataSet(df)
ds_lm.map_names()
ds_lm.normalize_components(by="total_mass(g)", inplace=True)

In [70]:
ds_lm.chemicals

,LiPF6,LiTFSI,LiFSI,LiPO2F2,LiBOB,LiBF4,LiTf,L1,LiTDI,LiDFOB,...,C2,C3,E1,DTD,Li2O,TFMB,DME,DOL,Al2O3,LiClO4
0,0.116000,0.000000,0.000000,0.000000,0.000000,0.0000,0.0,0.00000,0.000000,0.000000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.0
1,0.115000,0.000000,0.000000,0.000000,0.000000,0.0000,0.0,0.00000,0.000000,0.000000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.0
2,0.004592,0.119784,0.000000,0.000000,0.053903,0.0000,0.0,0.00000,0.000000,0.000000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.0
3,0.000000,0.000000,0.648295,0.000000,0.000000,0.0000,0.0,0.00000,0.000000,0.000000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.0
4,0.000000,0.229264,0.000000,0.000000,0.000000,0.0000,0.0,0.00000,0.000000,0.000000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.352895,0.417840,0.000000,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
732,0.037073,0.008508,0.015599,0.035811,0.009128,0.0000,0.0,0.03394,0.038154,0.000000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.021988,0.119919,0.000000,0.0
733,0.002980,0.056827,0.040092,0.000000,0.133612,0.0000,0.0,0.00000,0.000000,0.022382,...,0.0,0.0,0.0,0.0,0.0,0.0,0.041434,0.000000,0.000000,0.0
734,0.003100,0.108200,0.001700,0.002700,0.016600,0.0048,0.0,0.00000,0.015400,0.000000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.090800,0.017300,0.012700,0.0
735,0.000000,0.113500,0.006400,0.000000,0.051400,0.0000,0.0,0.00000,0.000000,0.000000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.480200,0.293200,0.000000,0.0
736,0.000000,0.108222,0.009602,0.002701,0.016603,0.0000,0.0,0.00000,0.015403,0.000000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.384077,0.234547,0.012703,0.0

In [266]:
df_chem = Chemical.from_csv("../chemicals/chemicals_database.csv")

In [267]:
select_chemicals = df_chem["Name"].isin(ds_lm.chemical_names) | df_chem["IUPAC"].isin(ds_lm.chemical_names)
select_elements = df_chem.columns.str.contains("ELE_") | df_chem.columns.isin(["Name", "Formula", "Type", "MW (g/mol)"])
df_chem.loc[select_chemicals, select_elements]

,Name,Formula,Type,MW (g/mol),ELE_H,ELE_Li,ELE_B,ELE_C,ELE_N,ELE_O,ELE_F,ELE_Si,ELE_P,ELE_S,ELE_Cl,ELE_Rb,ELE_Cs,ELE_Sn
0,Al2O3,Al2O3,additive,101.960,NaN,NaN,NaN,NaN,NaN,3.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,C1,CH4,additive,16.043,4.0,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,C2,C2H6,additive,30.070,6.0,NaN,NaN,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,C3,C3H8,additive,44.097,8.0,NaN,NaN,3.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,CsNO3,CsNO3,salt,194.910,NaN,NaN,NaN,NaN,1.0,3.0,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN
5,DTD,C2H2O3S,additive,124.120,2.0,NaN,NaN,2.0,NaN,3.0,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN
6,E1,NaN,additive,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,Li2O,Li2O4,additive,29.880,NaN,2.0,NaN,NaN,NaN,4.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,P2O5,P2O5,additive,283.900,NaN,NaN,NaN,NaN,NaN,5.0,NaN,NaN,2.0,NaN,NaN,NaN,NaN,NaN
10,S1,S,additive,32.060,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN
11,S2,S2,additive,32.060,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN
12,S3,S3,additive,32.060,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN
13,SN,Sn,additive,118.710,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0
14,TFMB,C14H10F6N2,additive,320.240,10.0,NaN,NaN,14.0,2.0,NaN,6.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,L1,Li,salt,6.997,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,Li2S,Li2S,salt,45.950,NaN,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN
18,LiAlO2,LiAlO2,salt,65.920,NaN,1.0,NaN,NaN,NaN,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21,LiBF4,LiBF4,salt,97.000,NaN,1.0,1.0,NaN,NaN,NaN,4.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
22,LiBOB,LiBC4O8,salt,194.000,NaN,1.0,1.0,4.0,NaN,8.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
23,LiClO4,LiClO4,salt,106.390,NaN,1.0,NaN,NaN,NaN,4.0,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN
24,LiDFOB,LiBF2(C2O4),salt,143.770,NaN,1.0,1.0,2.0,NaN,4.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
27,LiFSI,F2LiNO4S2,salt,187.000,NaN,1.0,NaN,NaN,1.0,4.0,2.0,NaN,NaN,2.0,NaN,NaN,NaN,NaN
28,LiNO3,LiNO3,salt,68.946,NaN,1.0,NaN,NaN,1.0,3.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
29,LiPF6,LiPF6,salt,152.000,NaN,1.0,NaN,NaN,NaN,NaN,6.0,NaN,1.0,NaN,NaN,NaN,NaN,NaN
30,LiPO2F2,LiPO2F2,salt,107.910,NaN,1.0,NaN,NaN,NaN,2.0,2.0,NaN,1.0,NaN,NaN,NaN,NaN,NaN
31,LiTDI,C6F3LiN4,salt,192.030,NaN,1.0,NaN,6.0,4.0,NaN,3.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
32,LiTf,CF3SO3Li,salt,156.010,NaN,1.0,NaN,1.0,NaN,3.0,3.0,NaN,NaN,1.0,NaN,NaN,NaN,NaN
34,LiTFSI,LiTFSI,salt,287.090,NaN,1.0,NaN,2.0,1.0,4.0,6.0,NaN,NaN,2.0,NaN,NaN,NaN,NaN
38,AN,CH3CN,solvent,41.054,3.0,NaN,NaN,2.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
39,BTC,C3Cl6O3,solvent,226.070,0.0,NaN,NaN,3.0,NaN,3.0,NaN,NaN,NaN,NaN,6.0,NaN,NaN,NaN
40,BTFE,CF3CH2)2O,solvent,182.072,4.0,NaN,NaN,4.0,NaN,1.0,6.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
41,BTFEC,C5H4F6O3,solvent,226.082,4.0,NaN,NaN,5.0,NaN,3.0,6.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
44,DEC,C5H10O3,solvent,118.130,10.0,NaN,NaN,5.0,NaN,3.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
49,diglyme,C6H14O3,solvent,134.175,14.0,NaN,NaN,6.0,NaN,8.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
52,DMC,C3H6O3,solvent,90.078,6.0,NaN,NaN,3.0,NaN,3.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
53,DMDMOS,C4H12O2Si,solvent,120.220,12.0,NaN,NaN,4.0,NaN,2.0,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN
54,DME,C4H10O2,solvent,90.120,10.0,NaN,NaN,4.0,NaN,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
57,DOL,C3H6O2,solvent,74.078,6.0,NaN,NaN,3.0,NaN,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
58,DTO,C2H4O3S,solvent,108.120,4.0,NaN,NaN,2.0,NaN,3.0,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN
60,EC,C3H4O3,solvent,88.062,4.0,NaN,NaN,3.0,NaN,3.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
62,EMC,C4H8O3,solvent,104.104,8.0,NaN,NaN,4.0,NaN,3.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
73,FEC,C3H3FO3,solvent,106.054,3.0,NaN,NaN,3.0,NaN,3.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
83,PC,C4H6O3,solvent,102.088,6.0,NaN,NaN,4.0,NaN,3.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
84,PS,(C8H8)x,solvent,101.000,8.0,NaN,NaN,8.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
86,Sulfolane,C4H8O2S,solvent,120.170,8.0,NaN,NaN,4.0,NaN,2.0,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN
91,TFEO,C7H7F9O3,solvent,310.126,7.0,NaN,NaN,7.0,NaN,3.0,9.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
93,TMP,C6H14O3,solvent,134.170,14.0,NaN,NaN,6.0,NaN,3.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
96,TMSNCS,C4H9NSSi,solvent,131.270,9.0,NaN,NaN,4.0,1.0,NaN,NaN,1.0,NaN,1.0,NaN,NaN,NaN,NaN
97,TMSPi,C9H27O3PSi3,solvent,298.540,21.0,NaN,NaN,9.0,NaN,3.0,NaN,3.0,1.0,NaN,NaN,NaN,NaN,NaN
98,TTE,C5H4F8O,solvent,232.082,4.0,NaN,NaN,5.0,NaN,1.0,8.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
100,VC,C3H2O3,solvent,86.046,2.0,NaN,NaN,3.0,NaN,3.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
102,Montmorillonite,Al2H2O12Si4,salt,360.310,2.0,NaN,NaN,NaN,NaN,12.0,NaN,4.0,NaN,NaN,NaN,NaN,NaN,NaN

# Extract Features

In [279]:
df_recipe_elements

,LiPF6,LiTFSI,LiFSI,LiPO2F2,LiClO4,LiBOB,LiBF4,LiTf,L1,LiTDI,...,S1,S2,S3,C1,C2,C3,E1,DTD,Li2O,TFMB
ELE_H,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,0.0,0.0,0.0,NaN,NaN,NaN,NaN
ELE_Li,0.0,0.000377,0.000051,0.000025,0.0,0.000086,0.0,0.0,0.0,0.00008,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
ELE_B,NaN,NaN,NaN,NaN,NaN,0.000086,0.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
ELE_C,NaN,0.000754,NaN,NaN,NaN,0.000342,NaN,0.0,NaN,0.000481,...,NaN,NaN,NaN,0.0,0.0,0.0,NaN,NaN,NaN,NaN
ELE_N,NaN,0.000377,0.000051,NaN,NaN,NaN,NaN,NaN,NaN,0.000321,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
ELE_O,NaN,0.001508,0.000205,0.00005,0.0,0.000685,NaN,0.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
ELE_F,0.0,0.002262,0.000103,0.00005,NaN,NaN,0.0,0.0,NaN,0.000241,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
ELE_Si,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
ELE_P,0.0,NaN,NaN,0.000025,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
ELE_S,NaN,0.000754,0.000103,NaN,NaN,NaN,NaN,0.0,NaN,NaN,...,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
ELE_Cl,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
ELE_Rb,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
ELE_Cs,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
ELE_Sn,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [332]:
recipes = ds_lm.dataframe
select_elements = df_chem.columns.str.contains("ELE_")

molar_elements_list = []
molar_elements_list_salt = []
molar_elements_list_solvent = []

for i in recipes.index:
    recipe = recipes.iloc[i] 
    recipe_elements = [] # molar amount of each element in each chemical in the recipe
    recipe_elements_salt = []
    recipe_elements_solvent = []
    for name in recipes.columns:
        if name not in ds_lm.chemical_names:
            continue
        try:
            # select chemical
            select_row = df_chem["Name"].isin([name]) | df_chem["IUPAC"].isin([name]) 
            chemical = df_chem.loc[select_row].squeeze().rename(name)
            # calculate total molar amount of the chemical
            molar_chemical = recipe[name] / chemical["MW (g/mol)"] # grams * (grams/mole)^-1
            # calculate total molar amount of each element in the chemical 
            molar_elements = chemical[select_elements] * molar_chemical 
            
            recipe_elements.append(molar_elements)
            if chemical["Type"] in ["solvent", "additive"]:
                recipe_elements_solvent.append(molar_elements)
            elif chemical["Type"] in ["salt"]:
                recipe_elements_salt.append(molar_elements)
        except:
            raise
    
    df_recipe_elements = pd.concat(recipe_elements, axis=1)
    molar_elements = df_recipe_elements.sum(axis=1)
    molar_elements["id"] = recipe["Electrolyte ID"]
    molar_elements_list.append(molar_elements)
    
    df_recipe_elements_salt = pd.concat(recipe_elements_salt, axis=1)
    molar_elements_salt = df_recipe_elements_salt.sum(axis=1)
    molar_elements_salt["id"] = recipe["Electrolyte ID"]
    molar_elements_list_salt.append(molar_elements_salt)

    df_recipe_elements_solvent = pd.concat(recipe_elements_solvent, axis=1)
    molar_elements_solvent = df_recipe_elements_solvent.sum(axis=1)
    molar_elements_solvent["id"] = recipe["Electrolyte ID"]
    molar_elements_list_solvent.append(molar_elements_solvent)

    print(i, end="\r", flush=True)

In [344]:
df_molar_elements = pd.concat(molar_elements_list, axis=1).T
df_molar_elements.set_index(keys="id", inplace=True)

df_molar_elements_salt = pd.concat(molar_elements_list_salt, axis=1).T
df_molar_elements_salt.set_index(keys="id", inplace=True)

df_molar_elements_solvent = pd.concat(molar_elements_list_solvent, axis=1).T
df_molar_elements_solvent.set_index(keys="id", inplace=True)

In [352]:
df_total_molar = df_molar_elements.sum(axis=1).to_frame(name="Total")
print(len(df_total_molar))
df_total_molar.head(5)

737

           Total
id
20-1-1  0.120832
20-1-2  0.120362
20-1-3  0.113810
20-1-4  0.081522
20-1-5  0.137477

In [354]:
df_molar_elements_solvent / df_total_molar.to_numpy()

,ELE_H,ELE_Li,ELE_B,ELE_C,ELE_N,ELE_O,ELE_F,ELE_Si,ELE_P,ELE_S,ELE_Cl,ELE_Rb,ELE_Cs,ELE_Sn
id,,,,,,,,,,,,,,
20-1-1,0.453936,0.0,0.0,0.268632,0.0,0.226905,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
20-1-2,0.451166,0.0,0.0,0.266995,0.0,0.225527,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
20-1-3,0.419713,0.0,0.0,0.242664,0.0,0.242664,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
20-1-4,0.287368,0.0,0.0,0.143684,0.0,0.143684,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
20-1-5,0.531011,0.0,0.0,0.237022,0.0,0.139026,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
21-7-564,0.440624,0.0,0.0,0.262004,0.0,0.182261,0.004686,0.000164,0.000055,0.006977,0.0,0.0,0.0,0.0
21-7-565,0.377573,0.0,0.0,0.229698,0.005264,0.144839,0.066055,0.0,0.0,0.006446,0.0,0.0,0.0,0.0
21-7-566,0.436888,0.0,0.0,0.251632,0.0,0.224005,0.002686,0.0,0.0,0.003702,0.0,0.0,0.0,0.0
21-7-567,0.546473,0.0,0.0,0.237726,0.0,0.134811,0.001341,0.0,0.0,0.001318,0.0,0.0,0.0,0.0
21-7-568,0.528687,0.0,0.0,0.235801,0.0,0.161461,0.00177,0.0,0.0,0.00313,0.0,0.0,0.0,0.0

In [ ]:
df_total_molar = df_molar_elements.iloc[:, :-1].sum(axis=1)
df_total_molar.name = "Total"
df_total_molar = pd.concat([df_molar_elements.iloc[:, -1], df_total_molar], axis=1)
df_total_molar.head(5)

       id     Total
0  20-1-1  0.120832
1  20-1-2  0.120362
2  20-1-3  0.113810
3  20-1-4  0.081522
4  20-1-5  0.137477

In [ ]:
df_total_molar = df_molar_elements.iloc[:, :-1].sum(axis=1)
df_total_molar.name = "Total"
df_total_molar = pd.concat([df_molar_elements.iloc[:, -1], df_total_molar], axis=1)
df_total_molar.head(5)

       id     Total
0  20-1-1  0.120832
1  20-1-2  0.120362
2  20-1-3  0.113810
3  20-1-4  0.081522
4  20-1-5  0.137477

In [104]:
for i in df_chem.index:
    chemical = df_chem.iloc[i]

{
    col.lstrip("ELE_"): int(df_DME[col].tolist()[0])
    for col in df_DME.columns if col.startswith("ELE_") and not np.isnan(df_DME[col].tolist()[0])
}

{'C': 4, 'H': 10, 'O': 2}